#services:
#  ridebooking-service:
#    build: .
#    container_name: ridebooking-app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ridebooking
#      SPRING_DATASOURCE_USERNAME: rideuser
#      SPRING_DATASOURCE_PASSWORD: ridepass
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}   # default is container Kafka
#    depends_on:
#      - postgres
#      - kafka
#
#  postgres:
#    image: postgres:15
#    container_name: ridebooking-db
#    environment:
#      POSTGRES_DB: ridebooking
#      POSTGRES_USER: rideuser
#      POSTGRES_PASSWORD: ridepass
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.5.0
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: confluentinc/cp-kafka:7.5.0
#    container_name: kafka
#    ports:
#      - "9093:9092" # host:container
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#    depends_on:
#      - zookeeper
#
#volumes:
#  postgres_data:

services:
  ridebooking-service:
    build: .
    container_name: ridebooking-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ridebooking
      SPRING_DATASOURCE_USERNAME: rideuser
      SPRING_DATASOURCE_PASSWORD: ridepass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}   # default is container Kafka
    depends_on:
      - postgres
      - kafka

  user-service:
    build: .
    container_name: user-service-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/uberdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: suraj@123
      JWT_SECRET: my-super-secret-in-docker
    depends_on:
      - mysql

  postgres:
    image: postgres:15
    container_name: ridebooking-db
    environment:
      POSTGRES_DB: ridebooking
      POSTGRES_USER: rideuser
      POSTGRES_PASSWORD: ridepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: suraj@123
      MYSQL_DATABASE: uberdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9093:9092" # host:container
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper

volumes:
  postgres_data:
  mysql_data: