#spring:
#  application:
#    name: user-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/uberdb
#    username: root
#    password: suraj@123   # or blank if still no password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
##    database-platform: org.hibernate.dialect.H2Dialect
#
#jwt:
#  secret: my-very-secret-key-that-should-be-very-long-256-bits
##  datasource:
##    url: jdbc:h2:mem:userdb
##    driver-class-name: org.h2.Driver
##    username: sa
##    password:



spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/uberdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:suraj@123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: ${JWT_SECRET:my-very-secret-key-that-should-be-very-long-256-bits}